### ISSUE TITLE
RGB图像test

### ISSUE THREAD

**Issue by muqiu791** [AWCXV/UNIFusion#1]
您好，我尝试使用您的模型融合一对RGBT图像，将in__c改成了3对应’RGB‘模式
但遇到了以下报错：
```
model_path: ./coco_pretrained.model
mode: RGB
Traceback (most recent call last):
  File "D:\Anaconda\envs\UNIF\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\Pycharm(Professional)\PyCharm 2022.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Pycharm(Professional)\PyCharm 2022.2.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\UNIFusion-main\test_imageTNO.py", line 205, in <module>
    main()
  File "E:\UNIFusion-main\test_imageTNO.py", line 173, in main
    model = load_model(model_path, in_c, out_c)
  File "E:\UNIFusion-main\test_imageTNO.py", line 20, in load_model
    nest_model.load_state_dict(torch.load(path))
  File "D:\Anaconda\envs\UNIF\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GhostFusion_net:
	size mismatch for conv1.primary_conv.1.weight: copying a param with shape torch.Size([8, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 3, 1, 1]).
	size mismatch for conv5.primary_conv.1.weight: copying a param with shape torch.Size([1, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 16, 1, 1]).
	size mismatch for conv5.cheap_operation.1.weight: copying a param with shape torch.Size([1, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([2, 1, 3, 3]).

```

使用的是您的的预训练模型coco_pretrained.model，也没有更改net网络文件，请问是什么原因？

**Comment by muqiu791** [comment]
环境与requirements的要求一致，在本地Windows 10系统下，GPU是3060
